import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-full">
        <div className="flex min-h-screen min-w-screen flex-col min-w-full bg-slate-100	!p-0">
          {children}
        </div>
      </body>
    </html>
  );
}
